q <- fread("exdata-data-household_power_consumption/household_power_consumption.txt", na.strings = "?")
q2 <- q[Date == "2/2/2007" | Date == "1/2/2007" ,]
q2[, DTIME := paste(Date,Time)]
png("plot4.png")
par(mfrow = c(2,2))
par(oma=c(1,1,1,1))
par(mar=c(5,4,4,4))
plot(q2[, strptime(DTIME, format="%d/%m/%Y %H:%M:%S")], q2[,Global_active_power], cex.lab = 0.7, cex.axis = 0.7, cex.main = 0.7, type="n", ylab="Global Active Power (kilowatts)",  xlab="")
lines(q2[, strptime(DTIME, format="%d/%m/%Y %H:%M:%S")], q2[,Global_active_power])
plot(q2[, strptime(DTIME, format="%d/%m/%Y %H:%M:%S")], q2[,Voltage], type="n",cex.lab = 0.7, cex.axis = 0.7, cex.main = 0.7,cex.sub=0.7,sub = "datetime", ylab="Voltage", xlab="")
lines(q2[, strptime(DTIME, format="%d/%m/%Y %H:%M:%S")], q2[,Voltage])
plot(q2[, strptime(DTIME, format="%d/%m/%Y %H:%M:%S")], q2[,Sub_metering_1], type="n",cex.lab = 0.7, cex.axis = 0.7, cex.main = 0.7, ylab="Energy sub metering", xlab="")
lines(q2[, strptime(DTIME, format="%d/%m/%Y %H:%M:%S")], q2[,Sub_metering_1])
lines(q2[, strptime(DTIME, format="%d/%m/%Y %H:%M:%S")], q2[,Sub_metering_2],col="red")
lines(q2[, strptime(DTIME, format="%d/%m/%Y %H:%M:%S")], q2[,Sub_metering_3],col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex=0.7, lty=c(1,1,1), lwd=c(1,1,1), col=c("black", "red", "blue") ) 
plot(q2[, strptime(DTIME, format="%d/%m/%Y %H:%M:%S")], q2[,Global_reactive_power], type="n",cex.lab = 0.7, cex.axis = 0.7, cex.main = 0.7, cex.sub = 0.7, sub = "datetime",xlab="", ylab="Global_reactive_power")
lines(q2[, strptime(DTIME, format="%d/%m/%Y %H:%M:%S")], q2[,Global_reactive_power] )
dev.off()